name: GPSD
description: Run gpsd in a container to expose GPS data over TCP
version: 0.2.2
slug: gpsd
url: https://github.com/dominikkukacka/ha-addon-gpsd
arch:
  - aarch64
  - armv7
  - armhf
  - amd64
startup: services
boot: auto
init: false
host_network: false

ports:
  2947/tcp: 2947
ports_description:
  2947/tcp: "gpsd TCP port"

full_access: true
apparmor: false

options:
  device: /dev/ttyUSB0
  baud: 9600
  gpsd_options: "-n"

schema:
  device: str
  baud: int
  gpsd_options: str
